[".oh-my-zsh"]
type = "archive"
url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"

[".asdf"]
type = "archive"
url = "https://github.com/asdf-vm/asdf/archive/v0.13.1.tar.gz"
exact = true
stripComponents = 1
